project_id = "dtdtwhrqvkrymtyqbatn"

[functions.get-voucher-campaigns-external]
verify_jwt = false

[functions.get-invoices-by-phone]
verify_jwt = false

[functions.get-customer-by-phone]
verify_jwt = false

[functions.check-voucher-eligibility]
verify_jwt = false

[functions.claim-voucher]
verify_jwt = false

[functions.voucher-history-customer]
verify_jwt = false

[functions.send-password-reset-email]
verify_jwt = false

[functions.create-user-account]
verify_jwt = true

[functions.send-new-user-credentials]
verify_jwt = false

[functions.invalidate-user-sessions]
verify_jwt = true

[functions.validate-employee-email]
verify_jwt = false

[functions.send-employee-otp]
verify_jwt = false

[functions.verify-employee-otp]
verify_jwt = false

[functions.send-payroll-notification]
verify_jwt = true
