project_id = "dtdtwhrqvkrymtyqbatn"

[functions.get-oauth-token]
verify_jwt = false

[functions.get-invoices-by-phone]
verify_jwt = false

[functions.get-customer-by-phone]
verify_jwt = false

[functions.check-voucher-eligibility]
verify_jwt = false

[functions.claim-voucher]
verify_jwt = false

[functions.voucher-history-customer]
verify_jwt = false
